import React, { useState } from 'react';
import "../styles/Faq.css";

import { Timeline } from 'primereact/timeline';
        



const FAQ = () => {
  const [activeIndex, setActiveIndex] = useState(null);

  const faqData = [
    {
      question: "What factors are considered in predicting car prices?",
      answer: "Car prices are determined by factors such as brand reputation, features, horsepower, mileage, and more."
    },
    {
      question: "Why is machine learning important in car price prediction?",
      answer: "Machine learning algorithms help analyze vast amounts of data to make accurate predictions based on various factors."
    },
    {
      question: "How can I benefit from accurate car price predictions?",
      answer: "Accurate predictions can help you make informed decisions when buying or selling cars, leading to better pricing strategies."
    },
    {
      question: "Is the prediction system accessible to everyone?",
      answer: "Our prediction system requires expertise in machine learning and access to computational resources for effective implementation."
    },
    {
      question: "Can the prediction system adapt to changes in the automotive industry?",
      answer: "Yes, the system can be updated with new data and algorithms to adapt to changes in the industry and improve prediction accuracy."
    },
    {
      question: "How accurate are the predictions generated by the system?",
      answer: "The accuracy of predictions depends on the quality of data, algorithms used, and understanding of industry factors, aiming for precise results."
    }
  ];

  return (
    <div className="parent-container">
      <div className="faq-container">
        <h2>FAQs</h2>
        <div className="product-info">SAYARTK INFO</div>
        {faqData.map((item, index) => (
          <div key={index} className="faq-item">
            <div className="faq-question" onClick={() => setActiveIndex(index === activeIndex ? null : index)}>
              {item.question}
              <i className={activeIndex === index ? "arrow up" : "arrow down"} />
            </div>
            <div className={`faq-answer ${activeIndex === index ? 'show' : ''}`}>
              {item.answer}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
export default FAQ;
